language: java
sudo: false
jdk: oraclejdk8
install: mvn ${SPARK} ${SCALA} -Dmaven.javadoc.skip=true -DskipTests=true -B -V -Dgpg.skip=true install
script: mvn ${SPARK} ${SCALA} -Dmaven.javadoc.skip=true -q -B -Dgpg.skip=true verify
env:
  global:
    - MAVEN_OPTS=-Xmx2g
# Use this to test future version of the 2.x Spark environment
# matrix:
#  include:
#    # Covers Spark 2.0.x 
#    - env: SPARK=-Dspark.version=2.0.0
cache:
  directories:
    - $HOME/.m2
